# AnarchyQueue V${project.version}
target: "main"
queue: "queue"
maxPlayers: 420
waitOnKick: 16
messagePosition: "&6Position in queue: &l%position%"
messageConnecting: "&6Connecting to the server..."
serverName: "0b0t"
kick: true
kickOnRestart: false
kickOnTooMany: false